services:
  client:
    build: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client:/app
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./server:/app
    command: npm run dev
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
